#!/usr/bin/env bash

# --- CONFIGURATION ---
# Add your project folders here
SEARCH_PATHS=(~/personal ~/work ~/work/aster ~/work/netsolution ~/.config)
# ---------------------

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # get running tmux sessions (excluding the current one)
    if [[ -n "$TMUX" ]]; then
        current_session=$(tmux display-message -p '#S')
        running_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | grep -v "^$current_session$")
    else
        running_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)
    fi

    # get directories from your search paths (direct children)
    candidate_dirs=$(find "${SEARCH_PATHS[@]}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)

    # combine them and pipe to FZF
    selected=$(echo -e "$running_sessions\n$candidate_dirs" | fzf)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi

# determine if the selection is directory or session Name
if [[ -d "$selected" ]]; then
    # it's a directory -> extract name and create session
    selected_name=$(basename "$selected" | tr . _)
    selected_path="$selected"
    
    # check if session already exists for this folder
    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected_path"
    fi
else
    # it's not a directory -> it must be an existing session name from the history list
    selected_name="$selected"
fi

# switch to the session
if [[ -z "$TMUX" ]]; then
    exec tmux attach-session -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
