#!/bin/bash

export PATH=$PATH:/home/szymon/.local/bin:/home/szymon/scripts

WALLPAPER_DIR="$HOME/Pictures/wallpapers"

preview_cmd="printf '\033_Ga=d\033\\'; chafa --format kitty --size \${FZF_PREVIEW_COLUMNS}x\${FZF_PREVIEW_LINES} {}"

SELECTED=$(find "$WALLPAPER_DIR" -type f | fzf \
  --layout=reverse \
  --preview-window=right:40% \
  --no-preview-border \
  --preview "$preview_cmd")

if [ -n "$SELECTED" ]; then
  wal-set "$SELECTED" > /dev/null 2>&1 * disown
fi

exit
